Ruby_on_Rails/Day06/ex00/LifeProTips/config/routes.rb
Rails.application.routes.draw do

  	resources :users, :only => [:new, :create, :user_params]
  	resources :sessions, :only => [:new, :create, :destroy]
	get '/register' => 'apllication2#register'
	get 'log_out' => 'sessions#destroy', :as => 'log_out'
	get 'log_in' => 'sessions#new', :as => 'log_in'
	get 'sign_up' => 'users#new', :as => 'sign_up'
	root :to => "users#new"

end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/models/user.rb
class User < ActiveRecord::Base


  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_length_of :password, :minimum => 8, :maximun => 20, :allow_blank => false
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_uniqueness_of :name

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/controllers/apllication2_controller.rb
class Apllication2Controller < ApplicationController
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	  def new
		  @animal_name = cookies[:user_name]
	  end

	  def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/controllers/users_controller.rb
require 'Nokogiri'
require 'open-uri'

class UsersController < ApplicationController

  def new
	  @user= User.new
	  url = "https://www.randomlists.com/random-animals"
	  doc = Nokogiri::HTML(open(url))
	  @animal_name = doc.css('li').first.css('span').text
		if cookies[:user_name].blank?
	   		cookies[:user_name] = { value: @animal_name, expires: 1.minute.from_now }
		else
			@animal_name = cookies[:user_name]
		end
  end

  def create
	  @user = User.new(user_params)
	  if @user.save
		  session[:user_id] = @user.id
		  @animal_name = session[:user_name]
		  redirect_to root_url, :notice => "signed up!"
	  else
		  render "new"
	  end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
 end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/helpers/apllication2_helper.rb
module Apllication2Helper
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/helpers/sessions_helper.rb
module SessionsHelper
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/helpers/users_helper.rb
module UsersHelper
end

Ruby_on_Rails/Day06/ex00/LifeProTips/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Day06</title>
  <!-- <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"> -->
  <link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
	  <% if current_user %>
	    Welcome <%= current_user.name %>.
	    <%= link_to "Log out", log_out_path %>
	  <% else %>
	  	Welcome <%= @animal_name%>_visitor.
	    <%= link_to "Sign up", sign_up_path %> or
	    <%= link_to "log in", log_in_path %>
	  <% end %>
	</div>

	<% flash.each do |name, msg| %>
	  <%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>



<%= yield %>

</body>
</html>

Ruby_on_Rails/Day06/ex00/LifeProTips/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>