Ruby_on_Rails/Day04/ex01/CheatSeet/config/routes.rb
Rails.application.routes.draw do

    root 'application2#convention'
    get '/console' => 'application2#console'
	get '/ruby' => 'application2#ruby'
	get '/ruby/numbers' => 'application2#numbers'
	get '/ruby/strings' => 'application2#strings'
	get '/ruby/arrays' => 'application2#arrays'
	get '/ruby/hashes' => 'application2#hashes'
	get '/rails' => 'application2#rails'
	get '/rails/rails_app' => 'application2#rails_app'
	get '/rails/rails_commands' => 'application2#rails_commands'
	get '/rails/embedded_ruby' => 'application2#embedded_ruby'
	get '/editor' => 'application2#editor'
	get '/quicksearch' => 'application2#quicksearch'

end

Ruby_on_Rails/Day04/ex01/CheatSeet/app/controllers/application2_controller.rb
#msd de securite
class Application2Controller < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def application
	@title = "Application"
end

def console
	@title = "Console"
end

def ruby
	@title = "Ruby"
end

def numbers
	@title = "Numbers"
end

def strings
	@title = "Strings"
end

def arrays
	@title = "Arrays"
end

def rails
	@title = "Rails"
end

def rails_app
	@title = "Rails App"
end

def rails_commands
	@title = "Rails_Commands"
end

def embedded_ruby
	@title = "ERB: Embedded Ruby"
end

def hashes
	@title = "Hashes"
end

def editor
	@title = "Editor Tips"
end

def quicksearch
	@title = "Quick Search"
end

end

Ruby_on_Rails/Day04/ex01/CheatSeet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
end

Ruby_on_Rails/Day04/ex01/CheatSeet/app/helpers/application2_helper.rb
#comm de secu
module Application2Helper
end

Ruby_on_Rails/Day04/ex01/CheatSeet/app/helpers/application_helper.rb
#comm de secu
module ApplicationHelper
end

Ruby_on_Rails/Day04/ex01/CheatSeet/app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
   <link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet" type="text/css">
 	<title><%=@title%></title>
  	<%= stylesheet_link_tag    'application', media: 'all'%>
  	<%= javascript_include_tag "application"%>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
	  <nav>
	    <div class="navbar navbar-fixed-top navbar-default"><div class="navbar-header"><a href="./#" class="navbar-brand cheat-sheet-brand">Rails Beginner Cheat Sheet</a></div>
	      <ul class="nav navbar-nav">
	        <li><%= link_to console_path do %>Console<%end%></li>
	        <li class="dropdown">
				<%= link_to ruby_path, class:"dropdown-toggle" do %><b class="caret"></b> Ruby<%end%>
	          <ul class="dropdown-menu">
				<li><%= link_to ruby_numbers_path do %>Numbers<%end%></li>
				<li><%= link_to ruby_strings_path do %>Strings<%end%></li>
				<li><%= link_to ruby_arrays_path do %>Arrays<%end%></li>
				<li><%= link_to ruby_hashes_path do %>hashes<%end%></li>
	          </ul>
	        </li>
	        <li class="dropdown">
				<%= link_to rails_path do %><b class="caret"></b> Rails<%end%>
	          <ul class="dropdown-menu">
				  <li><%= link_to rails_rails_app_path do %>Rails App<%end%></li>
				<li><%= link_to rails_rails_commands_path do %>Rails Commands<%end%></li>
				<li><%= link_to rails_embedded_ruby_path do %>ERB: Embedded Ruby<%end%></li>
	          </ul>
	        </li>
			<li><%= link_to editor_path do %>Editor Tips<%end%></li>
			<li><%= link_to quicksearch_path do %>Quick search<%end%></li>
	      </ul>
	      <ul class="nav pull-right navbar-nav">
	      </ul>
	    </div>
	  </nav>
	</div>
	<div id="content-wrapper">
	  <div class="container ">
	    <section id="main-content">
<%= yield %>
</section>
</div>
</div>
	<%= render "layouts/footer"%>
</body>
</html>